service: serverlesstesthelp
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  memorySize: 1536
  timeout: 300
  region: ap-northeast-2
functions:
  start:
    handler: src/index.handler
    environment:
      DEBUG: "*"
    events:
      - http:
          path: start
          method: get

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

plugins:
  - serverless-plugin-chrome

custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars
      - --ignore-certificate-errors
