service: simplecrawling

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 200
  timeout: 20
  region: ap-northeast-2
  apiGateway:
    minimumCompressionSize: 512
functions:
  saveIctCAU:
    handler: src/ictCAU.saveNotice
    events:
      - http:
          path: /saveIctCAUNotice
          method: get
          cors: true
  readIctCAU:
    handler: src/ictCAU.readNotice
    events:
      - http:
          path: /readIctCAUNotice
          method: get
          cors: true
  saveNurse:
    handler: src/nurse.saveNotice
    events:
      - http:
          path: /saveNurseNotice
          method: get
          cors: true
  readNurse:
    handler: src/nurse.readNotice
    events:
      - http:
          path: /readNurseNotice
          method: get
          cors: true
  getLibrary:
    handler: src/library.getLibrary
    events:
      - http:
          path: /getLibrary/{id}
          method: get
          cors: true
  getSubway:
    handler: src/subway.getSubway
    events:
      - http:
          path: /getSubway/{id}
          method: get
          cors: true
  getSubwayFirstLast:
    handler: src/subway.getSubwayFirstLast
    events:
      - http:
          path: /getSubwayFirstLast/{id}
          method: get
          cors: true
  getBus:
    handler: src/bus.getBus
    events:
      - http:
          path: /getBus/{id}
          method: get
          cors: true
  saveBne:
    handler: src/bne.saveNotice
    events:
      - http:
          path: /saveBneNotice
          method: get
          cors: true
  readBne:
    handler: src/bne.readNotice
    events:
      - http:
          path: /readBneNotice
          method: get
          cors: true
  saveCoe:
    handler: src/coe.saveNotice
    events:
      - http:
          path: /saveCoeNotice
          method: get
          cors: true
  readCoe:
    handler: src/coe.readNotice
    events:
      - http:
          path: /readCoeNotice
          method: get
          cors: true
  saveMed:
    handler: src/med.saveNotice
    events:
      - http:
          path: /saveMedNotice
          method: get
          cors: true
  readMed:
    handler: src/med.readNotice
    events:
      - http:
          path: /readMedNotice
          method: get
          cors: true
  saveScholarship:
    handler: src/scholarship.saveNotice
    events:
      - http:
          path: /saveScholarshipNotice
          method: get
          cors: true
  readScholarship:
    handler: src/scholarship.readNotice
    events:
      - http:
          path: /readScholarshipNotice
          method: get
          cors: true
  saveFood:
    handler: src/food.saveNotice
    events:
      - http:
          path: /saveFoodNotice
          method: get
          cors: true
  readFood:
    handler: src/food.readNotice
    events:
      - http:
          path: /readFoodNotice
          method: get
          cors: true
  getSchoolSchedule:
    handler: src/schoolSchedule.getSchoolSchedule
    events:
      - http:
          path: /getSchoolSchedule/{id}
          method: get
          cors: true
plugins:
  - serverless-offline
