service: simplecrawling

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 200
  timeout: 20
  region: ap-northeast-2
functions:
  saveIctCAU:
    handler: src/ictCAU.saveNotice
    events:
      - http:
          path: /saveictCAUNotice
          method: get
  readIctCAU:
    handler: src/ictCAU.readNotice
    events:
      - http:
          path: /readictCAUNotice
          method: get
  saveNurse:
    handler: src/nurse.saveNotice
    events:
      - http:
          path: /saveNurseNotice
          method: get
  saveBne:
    handler: src/bne.saveNotice
    events:
      - http:
          path: /saveBneNotice
          method: get
plugins:
  - serverless-offline
