service: portal

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 30
  region: ap-northeast-2
functions:
  all:
    handler: src/index.all
    events:
      - http:
          path: /all
          method: get
  cauNotice:
    handler: src/index.cauNotice
    events:
      - http:
          path: /cauNotice
          method: get
  notice:
    handler: src/index.notice
    events:
      - http:
          path: /notice
          method: get
  schoolSchedule:
    handler: src/index.schoolSchedule
    events:
      - http:
          path: /schoolSchedule
          method: get
  library:
    handler: src/index.library
    events:
      - http:
          path: /library
          method: get
package:
  include:
    - node_modules/**
plugins:
  - serverless-offline
