service: anothertest

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 30
  region: ap-northeast-2
functions:
  start:
    handler: src/index.handler
    events:
      - http:
          path: /start/{id}
          method: get
package:
  excludeDevDependencies: false
