service: ictcau

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 200
  timeout: 20
  region: ap-northeast-2
functions:
  ictCAU:
    handler: src/index.notice
    events:
      - http:
          path: /notice
          method: get
plugins:
  - serverless-offline
